version: '3.7'
services:
  mongodb:
    image: mongo
    container_name: colaMongo
    restart: always
    environment:
      - TZ=Asia/Shanghai    
    ports:
      - 27018:27017
    volumes:
      - ./opt/mongo/db:/data/db
    networks:
      colaNet:
        aliases:
          - mongo.cola.ai     
  esSingle:
    image: elasticsearch:7.6.1
    container_name: es_single
    # restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #set jvm ram usage
      - "discovery.type=single-node" #start as single node    
    volumes:
      - ./opt/es/config/es-single.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./opt/es/logs:/usr/share/elasticsearch/logs
      - ./opt/es/data:/usr/share/elasticsearch/data
      # - /opt/es/plugins:/usr/share/elasticsearch/plugins   
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      colaNet:
        aliases:
          - es.cola.ai      
  # esHead:
  #   image: mobz/elasticsearch-head:5
  #   container_name: es_head
  #   # restart: always
  #   depends_on:
  #     - esSingle
  #   ports: 
  #     - 9101:9100         
  nodeApi:
    image: fastify_cola
    container_name: cola.v1
    restart: always
    build: .
    command: "npm start"
    volumes:
      - ./opt/nodejs/.env:/usr/src/app/.env
      - ./opt/nodejs/logs:/usr/src/app/logs
    depends_on:
      - mongodb
      - esSingle
    ports:
      - 3699:3000
    environment:
      - TZ=Asia/Shanghai      
    networks:
      colaNet:
        aliases:
          - api.cola.ai

networks:
  colaNet:
    external:
      name: cola.ai